# Generated by Django 2.2.3 on 2019-07-31 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicbox', '0002_remove_playlist_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='songs',
        ),
    ]
