# Generated by Django 2.2.3 on 2019-07-31 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicbox', '0003_remove_playlist_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(help_text='Select a songs for this playlist', to='musicbox.Song'),
        ),
    ]
